---
# file: tasks.yml

  - name: install nginx
    apt: name=nginx-core state=present

  - name: configure default vhost
    copy:
      src: files/default
      dest: /etc/nginx/sites-available/default
    notify: restart nginx

  - name: enable default vhost
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link
    notify: restart nginx

  - name: copy index.html
    template:
      src: templates/index.html.j2
      dest: /var/www/html/index.html
